package graphics2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author Nasif
 */
public class DrawGraphics2D extends javax.swing.JFrame {

    /**
     * Creates new form DrawGraphics2D
     */
    public DrawGraphics2D() {
        initComponents();
    }
    
    private java.awt.Graphics2D g;
    private int x1, y1, x2, y2;
    Line2D LineBuffer;
    ArrayList <Line2D> linelist=new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lineradio = new javax.swing.JRadioButton();
        circleradio = new javax.swing.JRadioButton();
        rectangularradio = new javax.swing.JRadioButton();
        arcradio = new javax.swing.JRadioButton();
        polygonradio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        lineradio.setSelected(true);
        lineradio.setText("Line");

        circleradio.setText("Circle");

        rectangularradio.setText("Rectangle");

        arcradio.setText("Arc");

        polygonradio.setText("Polygon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lineradio)
                        .addGap(18, 18, 18)
                        .addComponent(circleradio)
                        .addGap(18, 18, 18)
                        .addComponent(rectangularradio)
                        .addGap(18, 18, 18)
                        .addComponent(arcradio)
                        .addGap(18, 18, 18)
                        .addComponent(polygonradio)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineradio)
                    .addComponent(circleradio)
                    .addComponent(rectangularradio)
                    .addComponent(arcradio)
                    .addComponent(polygonradio))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
        Graphics2D g = (Graphics2D) jPanel1.getGraphics();

        if (lineradio.isSelected()) {
            g.drawLine(0, 0, 100, 100);

            //g.draw(new Line2D.Double((double) 50.5, (double) 50.5, (double) 150.5, (double) 150.5));
        }
        
        if (circleradio.isSelected()) {
            g.drawOval(50, 50, 100, 100);
            g.setColor(Color.red);
            g.fillOval(50, 50, 100, 100);
        }
        
        if (rectangularradio.isSelected()) {
            //g.drawLine(0, 0, 100, 100);

            //g.draw(new Line2D.Double((double)50.5,(double)50.5,(double)150.5,(double)150.5));
            g.drawRect(10, 10, 150, 150);
            //g.drawRect(x1, y1, x2, y2);
            g.setColor(Color.green);
            g.fillRect(10, 10, 150, 150);
        }
        
        if (arcradio.isSelected()) {
            
            g.setStroke(new BasicStroke(2.0f));
            g.setPaint(Color.RED);
            g.drawArc(0, 0, 100, 100, 180, 180);
            //g.drawArc(0, 0, 100, 100, 0, 180);
            //g.fillArc(0, 0, 100, 100, 180, 180);                
        }
        
        if (polygonradio.isSelected()) {
            
            int xPoints[] = {100, 200, 300};
            int yPoints[] = {200, 50, 200};
            g.setColor(Color.yellow);
            g.drawPolygon(xPoints, yPoints, 3);
            g.fillPolygon(xPoints, yPoints, 3);
            
        }
        
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        
        g = (Graphics2D) jPanel1.getGraphics();
        x1 = evt.getX();
        y1 = evt.getY();
        
        if (! (lineradio.isSelected() || circleradio.isSelected() || rectangularradio.isSelected() || arcradio.isSelected() || polygonradio.isSelected() ) ) {         
           g.setPaint(Color.blue);
           g.drawRect(x1, y1, 50, 50);
        }
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        
        g=(Graphics2D) jPanel1.getGraphics();

        /*if (lineradio.isSelected()) {           // For Many lines
            jPanel1.update(g);
            x2 = evt.getX();
            y2 = evt.getY();
            LineBuffer=new Line2D.Double((double) x1, (double) y1, (double) x2, (double) y2);
            linelist.add(LineBuffer);
            draw();
            //g.draw(new Line2D.Double((double) x1, (double) y1, (double) x2, (double) y2));
        }*/
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

        if (lineradio.isSelected()) {
            jPanel1.update(g);
            x2 = evt.getX();
            y2 = evt.getY();
            g.draw(new Line2D.Double((double) x1, (double) y1, (double) x2, (double) y2));
        }
        
        for(int i=0;i<linelist.size();i++){
            draw();           
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    
    public void draw()
    {
        Iterator itr=linelist.iterator();
        Line2D L1=(Line2D)itr.next();
        for(int i=0;i<linelist.size();i++)
        {
            g.draw(linelist.get(i));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawGraphics2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawGraphics2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawGraphics2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawGraphics2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawGraphics2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arcradio;
    private javax.swing.JRadioButton circleradio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lineradio;
    private javax.swing.JRadioButton polygonradio;
    private javax.swing.JRadioButton rectangularradio;
    // End of variables declaration//GEN-END:variables
}
